# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'barrageDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for barrageDemo

  target 'barrageDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'BarrageRenderer', '~> 1.8.0'

end
